# Generated by Django 3.2.3 on 2021-05-17 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210517_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='userprofile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='name',
        ),
    ]
