# Generated by Django 3.2.3 on 2021-05-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210517_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='userprofile',
        ),
    ]
